# Generated by Django 3.2.3 on 2021-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='vid_id',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
